# PostgreSQL
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0pass
POSTGRES_HOST=db
POSTGRES_PORT=5432

# Redis
REDIS_PASSWORD=judge0redis
REDIS_HOST=redis
REDIS_PORT=6379

# Judge0
RAILS_ENV=production
RACK_ENV=production
SECRET_KEY_BASE=judge0secretkey1234567890abcdef1234567890abcdef
JUDGE0_TELEMETRY_ENABLE=false

MAX_QUEUE_SIZE=5000
MAX_RUNNERS=50
